module ChoresHelper
  def set_chores
    [ "Load the dishwasher",
      "Unload the dishwashe",
      "Sweep the kitchen floor",
      "Wipe the countertops",
      "Wipe appliance exteriors",
      "Polish the faucet",
      "Wipe out the sink",
      "Clean the junk drawer",
      "Toss away spoiled or expired food",
      "Wipe fingerprints from woodwork",
      "Clean windows",
      "Fold clean napkins and place mats",
      "Dust the table, chairs, and other furniture",
      "Dust artwork and collectibles",
      "Sweep the floor (if not carpeted)",
      "Wipe fingerprints from woodwork",
      "Clean windows",
      "Dust the blinds",
      "Polish the silver",
      "Dust the furniture",
      "Dust artwork and collectibles",
      "Sweep the floor (if not carpeted)",
      "Wipe fingerprints from woodwork",
      "Clean windows",
      "Dust the blinds",
      "Dust the TV and other electronics",
      "Corral the remotes",
      "Put CDS and DVDs away",
      "Dust houseplants",
      "Straighten magazines, books, and games",
      "Clean the mirror",
      "Wipe out the sink(s)",
      "Straighten makeup and jewelry drawers",
      "Empty the wastebasket",
      "Straighten up vanity top(s)",
      "Straighten up the linen closet",
      "Put soiled clothes in the hamper",
      "Hang up damp towels",
      "Clean windows",
      "Dust the blinds",
      "Straighten the bedspread",
      "Plump the pillows",
      "Dust dressers and nightstands",
      "Straighten up dressers and nightstands",
      "Dust artwork",
      "Clean windows",
      "Dust the blinds",
      "Rearrange a sock drawer",
      "Rearrange a lingerie drawer",
      "Rearrange a jewelry box",
      "Put soiled clothes in the hamper",
      "Hang clothes on hooks",
      "Put shoes away",
      "Empty the wastebasket",
      "Pick up around the hous",
      "Empty all wastebaskets",
      "Put toys in toy box",
      "Fold or wash a load of laundry",
      "Tackle ironing",
      "Dust the computer, keyboard, and printer",
      "Straighten the top of a desk",
      "Rearrange desk drawers",
      "Gather library books",
      "Stack newspapers for recycling",
      "Sweep the front porch",
      "Sweep the deck",
      "Mow the lawn",
      "Trim the bushes",
      "Help with landscaping projects, like spreading mulch or building a rock wall",
      "Weed the garden",
      "Wash the car",
      "Vacuum the car",
      "Clean outdoor furniture",
      "Get outdoor items out of storage and ready for use",
      "Gather unwanted items to donate or sell at a yard sale",
      "Wash outdoor items, like boats, ATVs, campers, or other outdoor items",
      "Rake the lawn",
      "Blow the leaves off the driveway",
      "Help clean the gutters",
      "Clean out the garden",
      "Clean outdoor items and help store them for winter",
      "Shovel snow",
      "Clean snow off of the car",
      "Vacuum living room, hallways, bedrooms, and stairs",
      "Sweep kitchen and bathroom floors",
      "Dust living room, bedrooms, and office space",
      "Vacuum the furniture",
      "Straighten the living room",
      "Shampoo carpets",
      "Organize drawers ",
      "Take care of items for recycling",
      "Take the trash out to the street for pick up",
      "Cook dinner (leave instructions)",
      "Wash and dry laundry",
      "Clean the kitchen counters",
      "Empty the dishwasher or wash dishes",
      "Clean the bathroom sink, mirror, and toilet",
      "Wash windows",
      "Clean refrigerator shelves and door; inside and out",
      "Mop floors",
      "Organize the food in the pantry",
      "Sanitize surfaces",
      "Organize the garage",
      "Organize bookshelves",
      "Water plants",
      "Feed the pet",
      "Walk the pet or clean litter",
      "Wash the pet or pet’s things",
      "Babysit younger siblings",
      "Make lunch for siblings",
      "Brush the pets outside to reduce shedding indoors"]
  end

  def set_priority
    ['High', 'Medium', 'Low']
  end

  def set_time_to_complete
    [5, 10, 15, 20, 30, 45, 60, 90, 120]
  end
end
